### ISSUE TITLE
A question about the regularizer.

### ISSUE THREAD

**Issue by Wentao-Xu** [MIRALab-USTC/KGE-DURA#2]
Since you mentioned before, h \overline{R} =(h_0r_0 - h_1r_1) + (h_0r_1 + h_1r_0) i, it can be seen as a complex vector where the real part is (h_0r_0 - h_1r_1) and the imaginary part is (h_0r_1 + h_1r_0), and the Euation (6) is the regularizer.

But why in [your code](https://github.com/MIRALab-USTC/KGE-DURA/blob/8c0a68532415c315825445e79a9891cd55768689/code/regularizers.py#L94) the ||h \overline{R}||_2^2 = h^2 * r^2 = (lhs[0] ^ 2 + lhs[1] ^ 2) * (rel[0] ^ 2 + rel[1] ^ 2) = (h_0 ^2 + h_1 ^ 2) * (r_0 ^ 2 + r_1 ^ 2)

Since h \overline{R} is a new complex vector, where the real part is (h_0r_0 - h_1r_1) and the imaginary part is (h_0r_1 + h_1r_0), are you sure that its L2 norm's square ||h \overline{R}||_2^2 = (h_0 ^2 + h_1 ^ 2) * (r_0 ^ 2 + r_1 ^ 2)= ||h||_2^2 * ||r||_2^2 ?

Did I misunderstand anything about the L2 norm of a complex vector?

**Comment by zq0x7a0x71** [comment]
||h||_2^2=h_0^2+h_1^2
||r||_2^2 =r_0^2+r_1^2
||h||_2^2 * ||r||_2^2 =h_0^2r_0^2+h_0^2r_1^2+h_1^2r_0^2+h_1^2r_1^2

||h \overline{R}||_2^2
=(h_0r_0 - h_1r_1)^2+(h_0r_1 + h_1r_0)^2
=(h_0r_0)^2+(h_1r_1)^2-2h_0r_0h_1r_1+(h_0r_1 )^2+(h_1r_0)^2+2h_0r_1h_1r_0
=(h_0r_0)^2+(h_1r_1)^2+(h_0r_1 )^2+(h_1r_0)^2

Obviously, the above two items are equal.

**Comment by Wentao-Xu** [comment]
OK, thanks for your reply, and it addresses my concern. 
The calculation of ||h||_2^2 * ||r||_2^2 is indeed more effcient than ||h \overline{R}||_2^2.
